export interface Expenses {
    id?: string,
    rev?: string,
    amountloaned: number,
    amountpayable: number,
    loanstatus: any,
    departmentname: string,
    staffname: string,
    staffposition: string,
    departmentloaning: string,
    dateofloan: any,
    expensename: string,
    amount: number,
    isoncredit: any,
    balance: number,
    expensetype: string,
    expenseproduct: string,
    expenseproductid: string,
    description: string,
    isonlinepayment: any,
    date: any,
    pending: any,
    staffloan: any,
    departmentloan: any,
    branch: string
}
