export interface LabProducts {
    id?: string,
    rev?: string,
    productname: string,
    productimage: string,
    suppliedin: string,
    productcategory: string,
    datesupplied: any,
    branch: string,
    store: string,
    dispatched: any,
    totalamountsupplied: number,
    dispatchdepartment: string,
    dispatchmethod: string,
    refund: any,
    quantityincartons: number,
    quantityinpackets: number,
    quantityperitems: number,
    datedispatched: any,
    sales: Array<any>
}
