export interface Sales {
    id?: string,
    rev?: string,
    department: string,
    amountloaned: number,
    amountpayable: number,
    loanstatus: any,
    departmentloaned: string,
    individualloanid: string,
    departmentloaning: string,
    departmentid: string,
    patientid: string,
    isreconciled: any,
    dateofloan: any,
    salename: string,
    amount: number,
    description: string,
    date: any,
    iscomplete: any,
    color: string,
    isowing: any,
    isoncredit:any,
    staffloan: any,
    departmentloan: any,
    balance: number,
    isevacuated: any,
    evacuatedmessage: string,
    branch: string,
    serviceorder: any,
    productorder: any,
    posproduct: any,
    referencenumber: any,
    products: Array<any>,
    services: Array<any>
}
