export interface Staff {
    id?: string,
    rev?: string,
    username: string,
    firstname: string,
    lastname: string,
    branch: string,
    department: string,
    dob: any,
    staffcode: string,
    position: string,
    password: string,
    salary: number,
    debt: number,
    accountnumber: string,
    bankaccount: string,
    mobile: string,
    address: string,
    email: string,
    dateofentry: any,
    sex: string,
    notification: Array<any>,
    expenses: Array<string>
}
